tqwewe/kameo

README.md
crates/kameo/benches/fibonacci.rs
crates/kameo/examples/basic.rs
crates/kameo/src/actor_ref.rs
crates/kameo/src/lib.rs
crates/kameo/src/message.rs
crates/kameo_macros/src/actor.rs
crates/kameo_macros/src/lib.rs

Previously, implementing `Message` and `Actor` were done on the message type itself.
```rust
impl Message<A> for M {
type Reply;
async fn handle(self, state: &mut A) -> Self::Reply;
}
```
This is quite confusing and unintuative to work with.
This PR changes the position of the actor and message type in the implementations so that `self` becomes the actor state.
```rust
impl Message<M> for A {
type Reply;
async fn handle(&mut self, msg: M) -> Self::Reply;
}
```

feat!: impl `Message` and `Query` for actor instead of message type

---

README.md
crates/kameo/Cargo.toml
crates/kameo/benches/fibonacci.rs
crates/kameo/examples/basic.rs
crates/kameo/examples/macro.rs
crates/kameo/examples/pool.rs
crates/kameo/src/actor_kind.rs
crates/kameo/src/actor_ref.rs
crates/kameo/src/error.rs
crates/kameo/src/lib.rs
crates/kameo/src/message.rs
crates/kameo/src/pool.rs
crates/kameo/src/spawn.rs
crates/kameo_macros/src/actor.rs
crates/kameo_macros/src/derive_actor.rs
crates/kameo_macros/src/derive_reply.rs
crates/kameo_macros/src/lib.rs

Merges the actors reply error into the `SendError` type, avoiding the need for `.await??` with double `?`'s.
Additionally removes the `nightly` feature flag, and implements `Reply` on many common types within the std lib, and provides a `Reply` derive macro.

Handler error

---

crates/kameo_macros/src/derive_reply.rs

The derive Reply include Sync trait, but BoxDebug doesn't include it.
```rust
#[inline]
fn into_boxed_err(self) -> ::std::option::Option<::std::boxed::Box<dyn ::std::fmt::Debug + ::std::marker::Send + ::std::marker::Sync + 'static>> {
::std::option::Option::None
}
```

Remove Sync trait from into_boxed_err method signature in DeriveReply

---

crates/kameo/src/actor.rs
crates/kameo/src/actor/actor_ref.rs
crates/kameo/src/actor/kind.rs
crates/kameo/src/actor/spawn.rs
crates/kameo/src/lib.rs

Previously, there was no guarantee that messages sent to an actors self within `Actor::on_start` would be processed first.
This PR implements internal buffering, introducing the guarantee that on_start messages will be processed first.
Eg:
```rust
impl Actor for MyActor {
async fn on_start(&mut self, actor_ref: ActorRef<Self>) -> Result<(), BoxError> {
tokio::time::sleep(Duration::from_secs(1)).await; // Wait 1 second
actor_ref.send_async(Say("hi from on_start"))?;
Ok(())
}
}
struct Say(&'static str);
impl Message<Say> for MyActor {
type Reply = ();
async fn handle(&mut self, Say(msg): Say, _ctx: Context<'_, Self, Self::Reply>) -> Self::Reply {
println!("{msg}");
}
}
async fn main() {
let my_actor_ref = kameo::spawn(MyActor::default());
my_actor_ref.send(Say("hi from main fn")).await?;
} …
```

feat: implement internal buffering whilst actor is starting up

---

crates/kameo/examples/blocking.rs
crates/kameo/src/actor/actor_ref.rs
crates/kameo/src/actor/kind.rs
crates/kameo/src/actor/spawn.rs
crates/kameo/src/error.rs
crates/kameo/src/message.rs

Closes https://github.com/tqwewe/kameo/issues/25.
Adds a method `Context::blocking` to execute blocking code within an actors handler.
https://github.com/tqwewe/kameo/blob/f89de4becc214b4652d923e7592ab2bd00fec4e9/crates/kameo/examples/blocking.rs#L23-L30

feat: add `Context::blocking` method for blocking actor code

---

crates/kameo/src/actor/actor_ref.rs
crates/kameo/src/actor/pool.rs
crates/kameo/src/error.rs
crates/kameo/src/message.rs

ActorRef's send methods which receive replies now return `SendResult`, allowing message replies to be either received asyncronously, or blocking.
```rust
actor_ref.send(msg).await?; // Async recv
actor_ref.send(msg).blocking_recv()?; // Blocking recv
```
Closes https://github.com/tqwewe/kameo/issues/25

feat!: return `SendError` from send methods allowing replies to be received blocking

---

README.md
crates/kameo/Cargo.toml
crates/kameo/benches/fibonacci.rs
crates/kameo/benches/overhead.rs
crates/kameo/examples/ask.rs
crates/kameo/examples/basic.rs
crates/kameo/examples/macro.rs
crates/kameo/examples/pool.rs
crates/kameo/examples/stream.rs
crates/kameo/src/actor.rs
crates/kameo/src/actor/actor_ref.rs
crates/kameo/src/actor/kind.rs
crates/kameo/src/actor/mailbox.rs
crates/kameo/src/actor/pool.rs
crates/kameo/src/actor/spawn.rs
crates/kameo/src/error.rs
crates/kameo/src/lib.rs
crates/kameo/src/message.rs
crates/kameo/src/reply.rs
crates/kameo/src/request.rs
crates/kameo/src/request/ask.rs
crates/kameo/src/request/query.rs
crates/kameo/src/request/tell.rs
crates/kameo_macros/src/derive_actor.rs
crates/kameo_macros/src/lib.rs

Closes https://github.com/tqwewe/kameo/issues/3 and https://github.com/tqwewe/kameo/issues/28
This PR changes how the fundamentals of kameo works, but adds support for choosing the boundedness of actor mailboxes. The actor mailbox can be set when implementing `Actor` with the `type Mailbox = BoundedMailbox<Self> or UnboundedMailbox<Self>` associated type.
As unbounded channels differ in asyncness than bounded channels, a new builder syntax has been introduced when sending messages to actors. The types are `AskRequest`, `TellRequest`, and `QueryRequest`. These are returned an ActorRef's with the `.ask(...)`, `.tell(...)`, `.query(...)` methods, and support customizing timeouts.
Sending a message with a reply would look like `my_actor_ref.ask(Foo { ... }).send().await?;`, and sending a …

feat!: add support for bounded/unbounded mailboxes

---

src/actor/actor_ref.rs
src/mailbox.rs

Fixes https://github.com/tqwewe/kameo/issues/45
As described in the issue, there was a panic that occured when using `attach_stream` on an actor that stops. This PR fixes this by using the `SendMessage` trait.
Additionally, the spawned tokio task stops when the stream returns `None`, and returns the stream.

fix!: `attach_stream` panicking when actor is stopped

---

examples/remote.rs
src/actor/actor_ref.rs
src/remote.rs
src/remote/swarm.rs
src/request/ask.rs
src/request/tell.rs

The purpose of this PR is to provide more flexibility to developers by exposing the libp2p `Multiaddr` directly instead of converting from a SocketAddr. This has some breaking changes, but overall provides more control.
**Features:**
- Use Multiaddr instead of SocketAddr
- Add `dial` method for dialing peers
- Return `SwarmFuture`, allowing `.await` to be omitted from swarm methods if the response can be ignored. This includes changing the swarm mpsc to unbounded so channel capacity doesn't have to be awaited.

feat!: use multiaddr and add `SwarmFuture`

---

README.md

First off, thanks for making Kameo! It's been great to use in my project.
I've tried to click these badges several times now to get to the crate page/docs/etc expecting it to be similar to how other repos link them, and been bamboozled by it just opening the badge image.
This updates the badges to link off to relevant locations, and adds a docs.rs badge for the api docs.

Add links to the README badges and add docs badge

---

src/actor/id.rs
src/remote/swarm.rs

- Rename `id` field to `sequence_id` for clarity
- Enhance documentation for ActorID struct and its methods
- Add new method `new_with_peer_id` for creating ActorID with specific peer
- Modify `to_bytes` and `from_bytes` methods to handle optional peer_id
- Make `ActorIDFromBytesError` public and improve its documentation
- Implement Serialize and Deserialize traits for ActorID
- Update error variant name from MissingInstanceID to MissingSequenceID
- Remove redundant Serialize and Deserialize derives from ActorID struct
This PR improves the overall structure and documentation of the ActorID
module, making it more consistent and easier to understand and use.

refactor: ActorID and improve documentation

---

README.md
docs.json
docs/distributed-actors.mdx
docs/distributed-actors/bootstrapping-actor-swarm.mdx
docs/distributed-actors/dialing-connecting-nodes.mdx
docs/distributed-actors/messaging-remote-actors.mdx
docs/distributed-actors/registering-looking-up-actors.mdx

As peer feedback, in-depth information on distributed actors in kameo was lacking. This PR adds sections to the kameo book covering how to use distributed actors, and how it works internally.
Sections added:
- Distributed Actors Overview
- Bootstrapping Actor Swarm
- Dialing and Connecting to Other Nodes
- Registering and Looking up Actors
- Messaging Remote Actors
Closes https://github.com/tqwewe/kameo/issues/50

docs: add in-depth distributed actors information to kameo book

---

Cargo.toml
README.md
src/actor.rs
src/actor/actor_ref.rs
src/actor/pool.rs
src/actor/pubsub.rs
src/actor/spawn.rs
src/message.rs
src/remote.rs
src/remote/swarm.rs

Updates code docs to add more examples and improved wording. Additionally, updates all examples to pass when running `cargo test --doc`.
Closes https://github.com/tqwewe/kameo/issues/49

docs: improve code docs and examples with all tests passing

---

.github/workflows/ci.yml
Cargo.toml
src/actor/actor_ref.rs
src/actor/id.rs
src/error.rs
src/lib.rs
src/request.rs
src/request/ask.rs
src/request/tell.rs

Closes #58 
Not sure if I made all unnecessary dependencies optional, maybe you'll have some suggestions on which other dependencies can be disabled.

Hide remote actor functionality behind "remote" feature

---

src/actor/actor_ref.rs
src/actor/spawn.rs

Closes https://github.com/tqwewe/kameo/issues/62
This adds the `wait_startup` method on `ActorRef`, which internally uses a `Semaphore` to synchronize actor startup with waiters.

feat: add `ActorRef::wait_startup` method

---

src/actor/actor_ref.rs
src/actor/pool.rs
src/actor/spawn.rs

This PR deprecates the existing `link_child`, `unlink_child`, `link_together`, and `unlink_together` methods on ActoRef in favor of the new `link` and `unlink` methods.
A new `spawn_link` function is also provided to ensure an actor is linked with another before being spawned.
The internal APIs used for spawning is also improved.

feat: add spawn_link and link/unlink functions

---

src/actor/actor_ref.rs
src/actor/pool.rs
src/mailbox.rs
src/mailbox/bounded.rs
src/mailbox/unbounded.rs
src/message.rs
src/request/ask.rs
src/request/tell.rs

This PR relaxes the implementation of the mailbox for the following traits:
- `MessageSend` :: `send`
- `TryMessageSend` :: `try_send`
- `BlockingMessageSend` :: `blocking_send`
- `TryBlockingMessageSend` :: `try_blocking_send`
Previously, sending a message to a generic actor reference required explicitly specifying the mailbox type:
```rust
async fn send_message<A, M>(actor_ref: ActorRef<A>, msg: M)
where
A: Actor + Message<M>,
M: Send + 'static,
{
let _ = actor_ref.tell(msg).send().await; // Error: `.send` isn't available here because the actor mailbox was not specified
}
```
To resolve this, the mailbox had to be declared as `A: Actor<Mailbox = BoundedMailbox<A>>`. However, this restricted flexibility when we wanted to support both bounded and unbounded mailboxes.
**With this PR, this …

feat!: relax request impls to be generic to any mailbox

---

src/actor/kind.rs
src/mailbox.rs
src/message.rs
src/reply.rs
src/request/ask.rs

Exposes a new `BoxReplySender` type alias with new method `.boxed()`, and additionally removes the `#[doc_hidden]` attributes on the `DynMessage` trait.

feat: add public `BoxReplySender` type alias

---

src/actor.rs
src/actor/spawn.rs
src/request/ask.rs

A new `PreparedActor` is returned from the `kameo::actor::prepare(actor)` function, which lets you run the actor locally in the current context, or spawned in a tokio task.

feat: add support for preparing an actor and running it outside a spawned task

---

src/actor/spawn.rs

The `spawn_with` function previously provided `&ActorRef<A>` as an argument, which was good for performance, however will always need to be cloned into the returned future. Without cloning, you'd get some annoying compile errors.
This PR makes it an owned `ActorRef<A>` to simplify the usage of `spawn_with`.

feat!: use owned actor ref in `spawn_with` function

---

src/actor/actor_ref.rs
src/request/ask.rs
src/request/tell.rs

Adds tracing warnings when an actor sends `.tell()` and `.ask()` requests to itself which may lead to a deadlock.

feat: add warnings for potential deadlocks

---

src/reply.rs

I don't know if it's oversight, but I think `std::path` types should also implement infallible `Reply`.

fix: implement infallible reply for `std::path` types

---

.github/workflows/ci.yml
Cargo.toml
src/actor/spawn.rs
src/lib.rs
src/remote/swarm.rs
src/request/ask.rs
src/request/tell.rs

- Split features into `default`, `macros`, `tracing`, and `remote` for better modularity
- Make `kameo_macros`, `once_cell`, and `tracing` optional dependencies
- Add conditional compilation for `tracing`-related code to avoid unnecessary dependencies
- Update CI workflow to test builds with different feature combinations
- Fix deadlock warnings to only log when both `debug_assertions` and `tracing` are enabled

refactor!: modularize features and improve conditional compilation

---

Cargo.toml
docs/distributed-actors/registering-looking-up-actors.mdx
examples/registry.rs
src/actor/actor_ref.rs
src/error.rs
src/lib.rs
src/registry.rs
src/remote/swarm.rs

Adds actor lookup and register functionality for local environments.
Closes https://github.com/tqwewe/kameo/issues/105
See example:
https://github.com/tqwewe/kameo/blob/b5da4bdbd8927cc7a3021cc8e4e94bf6cbe8f68b/examples/registry.rs#L10-L15

feat!: add local actor registry for non-remote environments

---

src/actor/actor_ref.rs

Adds `blocking_link` and `blocking_unlink` variants for synchronous code.

feat: add `blocking_link` and `blocking_unlink` methods to `ActorRef`

---

examples/manual_swarm.rs
macros/src/derive_remote_actor.rs
macros/src/remote_message.rs
src/actor.rs
src/actor/actor_ref.rs
src/actor/id.rs
src/actor/kind.rs
src/actor/spawn.rs
src/error.rs
src/mailbox.rs
src/remote.rs
src/remote/_internal.rs
src/remote/swarm.rs

feat!: add support for remote actor links

---

Cargo.toml

When the `remote` feature is not enabled, building the `remote` and `manual_swarm` examples failed.

Fix build whithout `remote` feature

---

Cargo.toml
src/actor/actor_ref.rs
src/actor/id.rs
src/actor/spawn.rs
src/remote/swarm.rs
src/request/ask.rs
src/request/tell.rs

Removes the use of interned peer ids, and instead simply references the actor swarm's peer ID whenever its needed. When serialized, the peer ID is included, so a deserialized peer ID should never be `local` if the actor swarm has been bootstrapped.
This also removes any need of "hydrating" actor IDs, which could be a potential cause for bugs if not used where it needs to be, and a performance issue if overused.

refactor!: remove internment dependency and simplify peer ID handling

---

src/reply.rs

It was only implemented for `Vec<T>`, but I guess it should also include other `std::collections` types.

fix: implement infallible replies for missing `std::collections` types

---

README.md
src/actor/spawn.rs
src/error.rs
src/mailbox.rs
src/mailbox/bounded.rs
src/message.rs
src/reply.rs
src/request.rs

I was snooping through the docs and code base to get a better understanding of Kameo and fixed a couple typos along the way.

docs: fix typos

---

examples/manual_swarm.rs
src/remote/swarm.rs

Adds a method to unregister actors under a given name.
Internally, this pushes a "tombstone" record to the DHT, and locally the record is deleted. After some time (at most 24 hours by default), the tombstone should be removed from the DHT.

feat!: add `unregister` method to `ActorSwarm`

---

Cargo.toml
macros/src/derive_reply.rs
src/actor/kind.rs
src/actor/pool.rs
src/actor/spawn.rs
src/error.rs
src/message.rs
src/reply.rs

Improved error handling of `PanicError` using a new `ReplyError` trait which requires all reply error types be `Debug + Send + 'static`.

feat!: add `ReplyError` trait for better `PanicError` downcasting

---

src/actor.rs
src/actor/kind.rs
src/actor/pool.rs
src/actor/spawn.rs

Most `Actor` trait methods previously returned `Option<ActorStopReason>`, where `Some` indicates the actor should stop running. However this isn't super clear. This enum has been replaced with `ControlFlow`, providing much more obvious behaviour with the `Continue` and `Break` variants.

feat!: use `ControlFlow` enum instead of `Option` for `Actor` methods

---

src/actor/id.rs
src/reply.rs

May be related to issue no. #64.
Trying to compile kameo for an ESP32 i got atomic support issues, which may be the same case for wasm (unsure, as i see 32 in the target name).
So i added:
* reply.rs: impl_infallible_reply based on atomic support on target
* actor/id.rs: use AtomicUsize and convert to 64-bit number
the second commit shows some danger if there is more actors (sequence_id) than usize supports (which practically will never happen, and if it happens a backtrace is thrown).
Behaviour is same on existing systems and added new support for 32, 16, 8 bit systems (without remote and tracing).
Hoping for a review.

Kameo for 32-bit embedded system and more!

---

README.md
benches/overhead.rs
docs/core-concepts/messages.mdx
docs/core-concepts/replies.mdx
docs/distributed-actors/messaging-remote-actors.mdx
docs/getting-started.mdx
examples/ask.rs
examples/basic.rs
examples/pool.rs
examples/pubsub.rs
examples/pubsub_filter.rs
examples/remote.rs
examples/stream.rs
macros/src/lib.rs
macros/src/messages.rs
src/actor/actor_ref.rs
src/actor/pool.rs
src/actor/pubsub.rs
src/actor/spawn.rs
src/message.rs
src/request/ask.rs
src/request/tell.rs

Fixes https://github.com/tqwewe/kameo/issues/143
As explained in the issue #143, sometimes the `async` keyword when implementing `Message` doesn't compile, and manually returning `-> impl Future<Output = Self::Reply> + Send` is necessary.
I don't understand exactly why, but removing the lifetime from `Context`, and instead borrowing mutably solves this, and as a bonus it removes the need for `'_` which can be considered slightly more user friendly and cleaner.

feat!: remove lifetime from `Context` and borrow mutably instead

---

examples/forward.rs
src/error.rs
src/lib.rs
src/message.rs
src/reply.rs
src/request/ask.rs

This PR uses the `ForwardMessageSend` trait for `Context::forward` method.
- uses the `ForwardMessageSend` trait for `Context::forward` method
- adds a `Context::forward_sync` method
- modifies the `ForwardedReply` type to be a struct
- adds `downcast_ok` and `downcast_err` methods to the `Reply` trait

feat!: use `ForwardMessageSend` trait for `Context::forward` methods

---

src/actor.rs
src/actor/kind.rs
src/actor/spawn.rs
src/error.rs

Adds an `Actor::next` method for processing messages beyond just the actors mailbox.

feat: add `Actor::next` method

---

actors/src/pool.rs
examples/manual_swarm.rs
src/actor/actor_ref.rs
src/actor/spawn.rs
src/error.rs
src/message.rs
src/remote.rs
src/remote/_internal.rs
src/remote/swarm.rs
src/request.rs
src/request/ask.rs
src/request/tell.rs

Adds a new `Recipient` type, which is returned by calling `ActorRef::recipeint()`, which provides a type erased actor ref, which supports a single message type.
This only supports `tell` requests as of now, since the reply types from ask requests could be different for each actor.
This PR also removes the error type generic from tell requests, since this variant is never created when using tell requests.
TODO:
Related: https://github.com/tqwewe/kameo/discussions/158#discussioncomment-12707953

feat!: add `Recipient` type for type erased actor refs

---

examples/broker.rs
examples/message_bus.rs
examples/pool.rs
examples/stream.rs
src/actor/actor_ref.rs
src/actor/spawn.rs
src/error.rs
src/request/ask.rs
src/request/tell.rs

Adds a new `wait_for_shutdown_result` method to `ActorRef`, for handling errors during shutdown. Additionally, exposes a `kameo::error::set_actor_error_hook` function for setting a global function to be called when an actor's `on_start` or `on_stop` methods return an error.
Closes https://github.com/tqwewe/kameo/issues/164
CC @vincent-tr

feat: add actor shutdown result handling and error hook

---

README.md
actors/src/broker.rs
actors/src/message_bus.rs
actors/src/pool.rs
actors/src/pubsub.rs
benches/overhead.rs
docs/core-concepts/actors.mdx
docs/distributed-actors/registering-looking-up-actors.mdx
examples/basic.rs
examples/broker.rs
examples/forward.rs
examples/macro.rs
examples/message_bus.rs
examples/pool.rs
examples/pubsub.rs
examples/pubsub_filter.rs
examples/registry.rs
examples/remote.rs
examples/stream.rs
macros/src/derive_actor.rs
src/actor.rs
src/actor/actor_ref.rs
src/actor/spawn.rs
src/lib.rs
src/mailbox.rs
src/request/ask.rs
src/request/tell.rs

Closes #167
A new `Args` type is added to the `Actor` trait, allowing the actors state to be initialized in the `on_start` method.
Unfortunately this makes the `on_start` method required, since it cannot have a default implementation. But the `#[derive(Actor)]` macro just sets the `Args = Self`, and returns the state in the implementation.
The spawn functions have been moved to be part of the `Actor` trait directly.
This means instead of `kameo::spawn(MyActor)`, you now use `MyActor::spawn(MyActor)`. This looks a little redundant, however the args passed to `MyActor::spawn(args)` can now be a different type to the actor itself, allowing some powerful patterns.
The spawn methods available are now:
- `Actor::spawn`
- `Actor::spawn_with_mailbox`
- `Actor::spawn_link`
- …

feat!: add `Actor::Args` associated type and actor spawn methods

---

src/actor/actor_ref.rs
src/request.rs
src/request/ask.rs
src/request/tell.rs

Implements `ReplyRecipient<M, OK, ERR>` in addition to `Recipient<M>` which can do ask requests. It is created in the same way as `Recipient` from `ActorRef` using `reply_recipient<M>()` method. `OK` and `ERR` generics are determined from corresponding `Message<M>::Reply`
Because it seems that some cases does not need ask requests (like message bus and broker) and reply types would interfere. So I decide that better to split it. `ReplyRecipient` can be "erased" to `Recipient` using `ReplyRecipient::erase_reply()` method.

feat(actor): add reply recipient that can do ask requests

---

src/actor/actor_ref.rs

Implements these traits on `ActorRef`, `RemoteActorRef`, `Recipient`, `ReplyRecipient`, `WeakActorRef`, `WeakRecipient`, `WeakReplyRecipient`.
Fixes https://github.com/tqwewe/kameo/issues/188

feat: implement `PartialEq`, `Eq`, and `Hash` for actor ref types

---

examples/manual_swarm.rs
examples/remote.rs
src/actor/actor_ref.rs
src/actor/spawn.rs
src/error.rs
src/registry.rs
src/remote/swarm.rs

Fixes https://github.com/tqwewe/kameo/issues/131
Uses kademlia providers to support multiple peers registering different actors under the same name.
Previously, registering an actor under an already occupied name would corrupt the DHT, and have somewhat undefined behaviour. This PR improves upon this edge case by using kademlia providers.
TODO:

feat!: add a `lookup_all` method to the actor registry using providers

---

.github/workflows/ci.yml

- Add explicit coverage for kameo_actors and kameo_macros crates
- Restructure CI matrix to use include for better control
- Add comprehensive feature combination testing for kameo
- Add workspace-wide formatting and clippy checks
- Fix missing clippy runs for kameo_actors crate
Resolves the issue where kameo_actors was not being linted, ensuring all three workspace crates (kameo, kameo_actors, kameo_macros) are properly built, tested, and linted.

ci: improve test and lint coverage for all workspace crates

---

src/actor/actor_ref.rs

fix: `stop_gracefully` panicking when actor is already stopped

---

src/actor/id.rs

Kind of small, though you can encapsulate these type of cases within code block. :)
Old Version
```rust
let peer_id_bytes = self
.peer_id
.peer_id()
.map(|peer_id| peer_id.to_bytes())
.or_else(|| ActorSwarm::get().map(|swarm| swarm.local_peer_id().to_bytes()));
#[cfg(feature = "remote")]
if let Some(peer_id_bytes) = peer_id_bytes {
bytes.extend(peer_id_bytes);
}
```
New Version 
```rust
#[cfg(feature = "remote")]
{
let peer_id_bytes = self
.peer_id()
.map(|peer_id| peer_id.to_bytes())
.or_else(|| ActorSwarm::get().map(|swarm| swarm.local_peer_id().to_bytes()));
if let Some(peer_id_bytes) = peer_id_bytes {
bytes.extend(peer_id_bytes);
}
}
```

chore(id): encapsulate remote feature behind feature flag

---

src/actor/actor_ref.rs
src/remote/behaviour.rs
src/remote/swarm.rs
src/request/tell.rs

- Make send() and try_send() fire-and-forget by default for better performance
- Add send_ack() and try_send_ack() methods for delivery acknowledgment
- Remove IntoFuture impl to force explicit choice between speed and reliability
BREAKING CHANGE: Remote tell requests no longer wait for acknowledgment by default.
Use send_ack() instead of send().await for the previous behavior.
Fixes performance issue where remote tell took ~1.6ms due to waiting for acknowledgment, making it unusable for high-frequency messaging.
Fixes https://github.com/tqwewe/kameo/issues/203

feat!: add fire-and-forget option for remote tell requests

---

Cargo.toml
src/registry.rs
src/remote.rs
src/remote/messaging.rs
src/remote/swarm.rs

Use std::sync::OnceLock
* Is the `Arc` really required for the static local registry? Does compile and test without it. But I assume this would be a breaking change to remove it.
* How about switching to a concurrent container to avoid Mutex overhead? Ractor uses a [DashMap](https://github.com/slawlor/ractor/blob/main/ractor/src/registry/pid_registry.rs#L46) but [scc](https://crates.io/crates/scc) may also be a good candidate. Maybe a read-optimized container like `HashIndex` or `TreeIndex`.

Remove dependency on once_cell

---

src/request/ask.rs

The `PendingReply` lifetime was never truly needed.

feat!: remove `PendingReply` lifetime

---

Cargo.toml
docs/distributed-actors/messaging-remote-actors.mdx
examples/custom_swarm.rs
examples/remote.rs
macros/Cargo.toml
macros/src/lib.rs
macros/src/remote_message.rs
src/remote/_internal.rs

With this PR, the `#[remote_message]` macro now no longer explitily needs a UUID set, and hashes the impl block to generate a short unique identifier. The hashed ID consists of `CRATE_NAME :: MAJOR_VERSION :: MODULE_PATH :: MESSAGE_TY :: ACTOR_TY :: ACTOR_GENERICS`.

feat(macros): hash remote_message impls to auto generate ids
